package com.example.MyBookShopApp.data;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.util.Date;

@Entity
@Table(name = "book_review")
@ApiModel(description = "The entity representing a review of books")
public class BookReview {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("Id generated by db automatically")
    private Integer id;

    @Column(name = "full_name")
    @ApiModelProperty("Full name of the review author")
    private String fullName;

    @Column(name = "book_rating")
    @ApiModelProperty("The rating of the book put in the review")
    private Integer bookRating;

    @Column(name = "review_date", columnDefinition = "TIMESTAMP")
    @ApiModelProperty("Date of publication of the review")
    private Date review_date;

    @Column(name = "review_text")
    @ApiModelProperty("Review text")
    private String reviewText;

    @Column(name = "likes")
    @ApiModelProperty("Number of likes")
    private Integer likes;

    @Column(name = "dislikes")
    @ApiModelProperty("Number of dislikes")
    private Integer dislikes;

    @ManyToOne
    @JoinColumn(name = "book_id",referencedColumnName = "id")
    @ApiModelProperty("Id of the book according to the current rating")
    private Book book;

    public BookReview() {
    }

    public BookReview(Integer id, String fullName, Integer bookRating, Date review_date,
                      String reviewText, Integer likes, Integer dislikes, Book book) {
        this.id = id;
        this.fullName = fullName;
        this.bookRating = bookRating;
        this.review_date = review_date;
        this.reviewText = reviewText;
        this.likes = likes;
        this.dislikes = dislikes;
        this.book = book;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public Integer getBookRating() {
        return bookRating;
    }

    public void setBookRating(Integer bookRating) {
        this.bookRating = bookRating;
    }

    public Date getReview_date() {
        return review_date;
    }

    public void setReview_date(Date review_date) {
        this.review_date = review_date;
    }

    public String getReviewText() {
        return reviewText;
    }

    public void setReviewText(String reviewText) {
        this.reviewText = reviewText;
    }

    public Integer getLikes() {
        return likes;
    }

    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    public Integer getDislikes() {
        return dislikes;
    }

    public void setDislikes(Integer dislikes) {
        this.dislikes = dislikes;
    }

    public Book getBook() {
        return book;
    }

    public void setBook(Book book) {
        this.book = book;
    }

    @Override
    public String toString() {
        return "BookReview{" +
                "id=" + id +
                ", fullName='" + fullName + '\'' +
                ", bookRating=" + bookRating +
                ", review_date=" + review_date +
                ", reviewText='" + reviewText + '\'' +
                ", likes=" + likes +
                ", dislikes=" + dislikes +
                ", book=" + book +
                '}';
    }
}
