package com.example.MyBookShopApp.data;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;

@Entity
@Table(name = "book_rating")
@ApiModel(description = "The entity representing the rating of books")
public class BookRating {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("Id generated by db automatically")
    private Integer id;

    @Column(name = "rating_one")
    @ApiModelProperty("Number of user reviews with a rating of one")
    private Integer ratingOne;

    @Column(name = "rating_two")
    @ApiModelProperty("Number of user reviews with a rating of two")
    private Integer ratingTwo;

    @Column(name = "rating_three")
    @ApiModelProperty("Number of user reviews with a rating of three")
    private Integer ratingThree;

    @Column(name = "rating_four")
    @ApiModelProperty("Number of user reviews with a rating of four")
    private Integer ratingFour;

    @Column(name = "rating_five")
    @ApiModelProperty("Number of user reviews with a rating of five")
    private Integer ratingFive;

    @ManyToOne
    @JoinColumn(name = "book_id",referencedColumnName = "id")
    @ApiModelProperty("Id of the book according to the current rating")
    private Book book;

    public BookRating() {
    }

    public Integer getRatingSum() {
        return ratingOne + ratingTwo + ratingThree + ratingFour + ratingFive;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getRatingOne() {
        return ratingOne;
    }

    public void setRatingOne(Integer ratingOne) {
        this.ratingOne = ratingOne;
    }

    public Integer getRatingTwo() {
        return ratingTwo;
    }

    public void setRatingTwo(Integer ratingTwo) {
        this.ratingTwo = ratingTwo;
    }

    public Integer getRatingThree() {
        return ratingThree;
    }

    public void setRatingThree(Integer ratingThree) {
        this.ratingThree = ratingThree;
    }

    public Integer getRatingFour() {
        return ratingFour;
    }

    public void setRatingFour(Integer ratingFour) {
        this.ratingFour = ratingFour;
    }

    public Integer getRatingFive() {
        return ratingFive;
    }

    public void setRatingFive(Integer ratingFive) {
        this.ratingFive = ratingFive;
    }

    public Book getBook() {
        return book;
    }

    public void setBook(Book book) {
        this.book = book;
    }

    @Override
    public String toString() {
        return "BookRating{" +
                "id=" + id +
                ", ratingOne=" + ratingOne +
                ", ratingTwo=" + ratingTwo +
                ", ratingThree=" + ratingThree +
                ", ratingFour=" + ratingFour +
                ", ratingFive=" + ratingFive +
                ", book=" + book +
                '}';
    }
}
